updating sdk LCD-79
tago-io/parse-decentlab pull request #3
Opened 2023-07-07 13:06 UTC by rafaelTelesS

* Updating sdk

2023-07-07 13:40 UTC, vitorfdl requested changes
As you are already updating the scripts, also make sure you update:

- Remove context.log or change to console.info, console.debug, etc..

2023-07-07 13:51 UTC, Freddyminu commented on README.md
>  This analysis retrieves the device list of your account and print to the console.
This analysis retrieves the device list of your account and prints it in the console.

2023-07-07 13:51 UTC, Freddyminu commented on README.md
> +   1 - Click in the button "Add Policy" in this url: https://admin.tago.io/am;
1 - Click the the button "Add Policy" at this url: https://admin.tago.io/am;

2023-07-07 13:53 UTC, Freddyminu commented on README.md
> +   2 - In the Target select Analysis with the field Id and choose your analysis in the list;
2 - In the Target selector, select the Analysis with the field set as "ID" and choose your Analysis in the list;

2023-07-07 13:55 UTC, Freddyminu commented on README.md
> +   3 - Click in "Click to add a new permission" and select "Device" with rules "Access" with the field "Any";
3 - Click the  "Click to add a new permission" element and select "Device" with the rule "Access" with the field as "Any";

2023-07-07 13:56 UTC, Freddyminu commented on README.md
> +   4 - To finish click on save;<br>
4 - To save your new Policy, click the save button in the bottom right corner;<br>

2023-07-07 13:58 UTC, Freddyminu commented on analysis.js
>   ** This analysis retrieves the device list of your account and print to the console.
** This analysis retrieves a list of devices from your account and prints it to the console.

2023-07-07 13:58 UTC, Freddyminu commented on analysis.js
> + **  4 - To finish click on save;
so colar as correções do readme para aqui ja que so ta repetindo de la

2023-07-07 14:00 UTC, Freddyminu commented
Olhei o read me e ta meio estranho, acho que faltou quebra de linha: 

![image](https://github.com/tago-io/analysis-example-devicelist/assets/33817929/573bba3b-8ae2-4eea-858f-af9cfede487b)

2023-07-07 14:10 UTC, Freddyminu approved these changes

2023-07-13 13:57 UTC, vitorfdl approved these changes

2023-07-13 13:57 UTC, merged